### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ciweigg2** [amehime/hexo-theme-shoka#1]
ERROR Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk)
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk)
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk)
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 48, Column 29]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 23, Column 18]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk)
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 8, Column 26]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 26, Column 32]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 46, Column 19]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 69, Column 17]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/_partials/sidebar/overview.njk) [Line 45, Column 12]
  Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/_partials/sidebar/menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:51:3)
    at Template.render (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:550:10)
    at /Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/scripts/renderer/njk.js:41:29
    at _View._compiled (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:491:10)
    at resume_ (_stream_readable.js:976:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'Template render error'
}

所有依赖都安装了 不知道还缺什么

**Comment by amehime** [comment]
请把主题配置config.yml里的menu部分复制给我看一下吧 amehime 邮箱：ameosly@gmail.com 签名由 网易邮箱大师 定制 在2020年09月23日 16:44，ciweigg2 写道： ERROR Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 48, Column 29] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 23, Column 18] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 8, Column 26] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 26, Column 32] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 46, Column 19] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/page.njk) [Line 69, Column 17] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/_partials/sidebar/overview.njk) [Line 45, Column 12] Template render error: (/Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/layout/_partials/sidebar/menu.njk) [Line 3, Column 31] TypeError: Cannot read property 'replace' of undefined at Object._prettifyError (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/lib.js:36:11) at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:561:19 at Template.root [as rootRenderFunc] (eval at _compile (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:631:18), :51:3) at Template.render (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/nunjucks/src/environment.js:550:10) at /Users/maxiucheng/Documents/博客/ciweiblog/blog/themes/shoka/scripts/renderer/njk.js:41:29 at _View._compiled (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/theme/view.js:136:50) at _View.render (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/theme/view.js:39:17) at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/hexo/index.js:64:21 at tryCatcher (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/bluebird/js/release/util.js:16:23) at /Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/bluebird/js/release/method.js:15:34 at RouteStream._read (/Users/maxiucheng/Documents/博客/ciweiblog/blog/node_modules/hexo/lib/hexo/router.js:47:5) at RouteStream.Readable.read (stream_readable.js:491:10) at resume (_stream_readable.js:976:12) at processTicksAndRejections (internal/process/task_queues.js:80:21) { name: 'Template render error' } 所有依赖都安装了 不知道还缺什么 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by amehime** [comment]
请把主题配置config.yml里的menu部分复制给我看一下吧

**Comment by ciweigg2** [comment]
嗯 menu出的问题 我已经改了 现在遇到别的问题了 能否留个联系方式支持下 谢谢大佬

**Comment by amehime** [comment]
抱歉哇，因为个人工作和学习都比较忙，不是一直有网络和电脑那种（捂脸。。有问题的话可以这边发issue或者博客那边留言或者发邮件给我，我看到后会第一时间回复的！
